FROM node:alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install # npm ci 대신 npm install 사용
RUN npm install typescript # TypeScript 설치
COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./default.conf /etc/nginx/conf.d
COPY --from=builder /app/dist /usr/share/nginx/html