name: Deploy Frontend

on:
  push:
    branches: [ "main", "dev", "dev2", "build/**" ]
  pull_request:
    branches: [ "main", "dev", "dev2", "build/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: frontend docker build and push
        run: |
          cd ./front
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_REPOSITORY }}:frontend .
          docker push ${{ secrets.DOCKER_REPOSITORY }}:frontend