name: Deploy Frontend

on:
  push:
    branches: [ "main", "dev", "dev2", "build/**" ]
  pull_request:
    branches: [ "main", "dev", "dev2", "build/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: frontend docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_REPOSITORY }}:frontend ./front
          docker push ${{ secrets.DOCKER_REPOSITORY }}:frontend

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.AWS_DEV_HOSTNAME }}
          key: ${{ secrets.AWS_DEV_PRIVATE_KEY }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/frontend
            docker-compose up -d
            docker image prune -f